version: "3.2"

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "passhope"
      POSTGRES_DB: "hope"
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - postgres-compose
    volumes:
      - ./:/home/node/app
    ports:
      - "8000:8040"
    command: "npm start"
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge